#!/usr/bin/env python3
"""
phase2.py -- Phase 2, Experiments 1 and 2.

Exp 1: BUY-only filter   -> signals_buyonly.csv
Exp 2: BUY-only + UP-regime gate -> signals_buyonly_upregime.csv

Loads signals.csv (already generated by backtest.py), applies filters,
saves new CSVs, and prints summary stats for all three sets side by side.
"""
import csv
import math
import sys
from collections import defaultdict
from pathlib import Path
from statistics import median, stdev

import pandas as pd

REPO = Path(__file__).parent

DATA_DIR    = REPO / 'data'
RESULTS_DIR = REPO / 'results'
SIGNALS_CSV          = RESULTS_DIR / 'signals.csv'
BUYONLY_CSV          = RESULTS_DIR / 'signals_buyonly.csv'
BUYONLY_UPREGIME_CSV = RESULTS_DIR / 'signals_buyonly_upregime.csv'

TICKERS = [
    'AAPL', 'MSFT', 'NVDA', 'GOOGL', 'META',
    'JPM',  'XOM',  'JNJ',  'WMT',   'V',
    'SPY',  'QQQ',  'IWM',  'DIA',
    'TSLA', 'COIN', 'SOFI', 'PLTR',
    'KO',   'PG',
]

CSV_COLS = [
    'ticker', 'date', 'direction', 'confidence',
    'entry_price', 'stop_price', 'tp1', 'tp2',
    'spread_cost_pct', 'slippage_pct',
    'outcome', 'exit_price', 'r_multiple', 'hold_bars', 'set',
]

_FLOAT_COLS = {'confidence', 'entry_price', 'stop_price', 'tp1', 'tp2',
               'spread_cost_pct', 'slippage_pct', 'exit_price', 'r_multiple'}
_INT_COLS   = {'hold_bars'}


def load_records(path: Path) -> list:
    recs = []
    with open(path, newline='') as f:
        for row in csv.DictReader(f):
            for col in _FLOAT_COLS:
                if col in row:
                    row[col] = float(row[col])
            for col in _INT_COLS:
                if col in row:
                    row[col] = int(row[col])
            recs.append(row)
    return recs


def save_records(recs: list, path: Path) -> None:
    with open(path, 'w', newline='') as f:
        w = csv.DictWriter(f, fieldnames=CSV_COLS)
        w.writeheader()
        w.writerows(recs)
    print(f'Wrote {len(recs):,} records -> {path.name}')


def build_regime_map() -> dict:
    """Return dict keyed (ticker, date_str) -> 'UP' | 'DOWN' | 'UNKNOWN'."""
    regime_map: dict = {}
    for tk in TICKERS:
        path = DATA_DIR / f'{tk}_daily.parquet'
        if not path.exists():
            continue
        df = pd.read_parquet(path)
        sma50     = df['close'].rolling(50).mean()
        sma50_lag = sma50.shift(20)
        regime    = pd.Series('DOWN', index=df.index, dtype=str)
        valid     = sma50.notna() & sma50_lag.notna()
        regime[valid & (sma50 > sma50_lag)] = 'UP'
        regime[~valid] = 'UNKNOWN'
        for ts, reg in regime.items():
            regime_map[(tk, str(ts.date()))] = reg
    return regime_map


def _stats_block(recs: list, label: str) -> None:
    if not recs:
        print(f'\n{label}: no signals\n')
        return

    total  = len(recs)
    n_buy  = sum(1 for r in recs if r['direction'] == 'BUY')
    n_sell = total - n_buy

    tp1    = [r for r in recs if r['outcome'] == 'TP1_HIT']
    tp2    = [r for r in recs if r['outcome'] == 'TP2_HIT']
    stops  = [r for r in recs if r['outcome'] == 'STOP_HIT']
    expiry = [r for r in recs if r['outcome'] == 'EXPIRED']
    wins   = tp1 + tp2

    wr    = len(wins)  / total * 100
    tp1r  = len(tp1)   / total * 100
    tp2r  = len(tp2)   / total * 100
    stopr = len(stops) / total * 100
    expr  = len(expiry)/ total * 100

    rs      = [r['r_multiple'] for r in recs]
    win_rs  = [r['r_multiple'] for r in wins]
    loss_rs = [r['r_multiple'] for r in stops]

    mean_r  = sum(rs) / len(rs)
    med_r   = median(rs)
    avg_win = sum(win_rs)  / len(win_rs)  if win_rs  else 0.0
    avg_los = sum(loss_rs) / len(loss_rs) if loss_rs else 0.0
    exp_r   = (len(wins)/total) * avg_win + (len(stops)/total) * avg_los

    date_r: dict = defaultdict(float)
    for r in recs:
        date_r[r['date']] += r['r_multiple']
    daily_rs = list(date_r.values())
    if len(daily_rs) > 1:
        std_r  = stdev(daily_rs)
        sharpe = (sum(daily_rs)/len(daily_rs)) / std_r * math.sqrt(252) if std_r > 1e-9 else 0.0
    else:
        sharpe = 0.0

    chron_r    = [r['r_multiple'] for r in sorted(recs, key=lambda x: x['date'])]
    max_consec = cur_consec = 0
    for v in chron_r:
        if v < 0:
            cur_consec += 1
            max_consec = max(max_consec, cur_consec)
        else:
            cur_consec = 0

    by_ticker = defaultdict(list)
    for r in recs:
        by_ticker[r['ticker']].append(r)

    W = 60
    print(f'\n{"="*W}')
    print(f'  {label}')
    print(f'{"="*W}')
    print(f'  Total signals : {total:,}  (BUY {n_buy:,} / SELL {n_sell:,})')
    print(f'  Outcomes      : TP1 {tp1r:.1f}%  TP2 {tp2r:.1f}%  '
          f'STOP {stopr:.1f}%  EXPIRED {expr:.1f}%')
    print(f'  Win rate      : {wr:.1f}%  (TP1+TP2)')
    print(f'  Mean R        : {mean_r:+.4f}')
    print(f'  Median R      : {med_r:+.4f}')
    print(f'  Avg win R     : {avg_win:+.4f}')
    print(f'  Avg loss R    : {avg_los:+.4f}')
    print(f'  Expectancy    : {exp_r:+.4f} R')
    print(f'  Sharpe (ann.) : {sharpe:+.3f}')
    print(f'  Max consec L  : {max_consec}')
    print(f'  Avg hold bars : {sum(r["hold_bars"] for r in recs)/total:.1f}')
    print(f'\n  {"Ticker":<6}  {"Sigs":>5}  {"Buy":>4}  {"Sell":>4}  '
          f'{"Win%":>6}  {"MeanR":>7}  {"Exp R":>7}')
    print(f'  {"-"*52}')
    for tk in TICKERS:
        tr = by_ticker.get(tk, [])
        if not tr:
            continue
        tw   = [x for x in tr if x['outcome'] in ('TP1_HIT', 'TP2_HIT')]
        tl   = [x for x in tr if x['outcome'] == 'STOP_HIT']
        twr  = len(tw) / len(tr) * 100
        tmr  = sum(x['r_multiple'] for x in tr) / len(tr)
        taw  = sum(x['r_multiple'] for x in tw) / len(tw) if tw else 0.0
        tal  = sum(x['r_multiple'] for x in tl) / len(tl) if tl else 0.0
        texr = (len(tw)/len(tr))*taw + (len(tl)/len(tr))*tal
        tbu  = sum(1 for x in tr if x['direction'] == 'BUY')
        tse  = len(tr) - tbu
        print(f'  {tk:<6}  {len(tr):>5}  {tbu:>4}  {tse:>4}  '
              f'{twr:>5.1f}%  {tmr:>+7.4f}  {texr:>+7.4f}')
    print(f'{"="*W}')


def main() -> None:
    if not SIGNALS_CSV.exists():
        sys.exit(f'ERROR: {SIGNALS_CSV} not found. Run backtest.py first.')

    print('Loading signals.csv ...')
    all_recs = load_records(SIGNALS_CSV)
    print(f'  {len(all_recs):,} total signals loaded')

    # ── Experiment 1: BUY-only ────────────────────────────────────────────────
    print('\n-- Experiment 1: BUY-only filter --')
    buyonly = [r for r in all_recs if r['direction'] == 'BUY']
    save_records(buyonly, BUYONLY_CSV)

    # ── Experiment 2: BUY-only + UP-regime ───────────────────────────────────
    print('\n-- Experiment 2: BUY-only + UP-regime gate --')
    print('Building regime map from daily parquet files ...')
    regime_map = build_regime_map()
    buyonly_up = [
        r for r in buyonly
        if regime_map.get((r['ticker'], r['date']), 'UNKNOWN') == 'UP'
    ]
    n_unknown = sum(
        1 for r in buyonly
        if regime_map.get((r['ticker'], r['date']), 'UNKNOWN') == 'UNKNOWN'
    )
    n_down = len(buyonly) - len(buyonly_up) - n_unknown
    print(f'  BUY signals: {len(buyonly):,} total -> UP {len(buyonly_up):,} '
          f'/ DOWN {n_down:,} / UNKNOWN {n_unknown:,}')
    save_records(buyonly_up, BUYONLY_UPREGIME_CSV)

    # ── Side-by-side stats ────────────────────────────────────────────────────
    val_cutoff = min(r['date'] for r in all_recs if r['set'] == 'val')

    train_all = [r for r in all_recs  if r['set'] == 'train']
    val_all   = [r for r in all_recs  if r['set'] == 'val']
    train_buy = [r for r in buyonly   if r['set'] == 'train']
    val_buy   = [r for r in buyonly   if r['set'] == 'val']
    train_buu = [r for r in buyonly_up if r['set'] == 'train']
    val_buu   = [r for r in buyonly_up if r['set'] == 'val']

    print(f'\n\n{"#"*60}')
    print('  RESULTS: ALL THREE SETS SIDE BY SIDE')
    print(f'  Val cutoff: {val_cutoff}')
    print(f'{"#"*60}')

    print('\n\n>>> SET A: ORIGINAL (all signals, Phase 1D baseline) <<<')
    _stats_block(train_all, f'ORIGINAL -- TRAINING SET  (before {val_cutoff})')
    _stats_block(val_all,   f'ORIGINAL -- VALIDATION SET  (from {val_cutoff})')

    print('\n\n>>> SET B: BUY-ONLY (Experiment 1) <<<')
    _stats_block(train_buy, f'BUY-ONLY -- TRAINING SET  (before {val_cutoff})')
    _stats_block(val_buy,   f'BUY-ONLY -- VALIDATION SET  (from {val_cutoff})')

    print('\n\n>>> SET C: BUY-ONLY + UP-REGIME (Experiment 2) <<<')
    _stats_block(train_buu, f'BUY+UPREGIME -- TRAINING SET  (before {val_cutoff})')
    _stats_block(val_buu,   f'BUY+UPREGIME -- VALIDATION SET  (from {val_cutoff})')

    # ── Compact comparison table ──────────────────────────────────────────────
    def _summary_row(label, train_r, val_r):
        def _exp(recs):
            if not recs:
                return 0.0, 0.0
            wins  = [r for r in recs if r['outcome'] in ('TP1_HIT', 'TP2_HIT')]
            stops = [r for r in recs if r['outcome'] == 'STOP_HIT']
            aw = sum(r['r_multiple'] for r in wins)  / len(wins)  if wins  else 0.0
            al = sum(r['r_multiple'] for r in stops) / len(stops) if stops else 0.0
            wr = len(wins) / len(recs)
            sr = len(stops) / len(recs)
            return wr * 100, wr * aw + sr * al

        tr_wr, tr_ex = _exp(train_r)
        va_wr, va_ex = _exp(val_r)
        print(f'  {label:<28}  '
              f'train N={len(train_r):>5}  WR={tr_wr:>5.1f}%  Exp={tr_ex:>+7.4f} R  |  '
              f'val N={len(val_r):>4}  WR={va_wr:>5.1f}%  Exp={va_ex:>+7.4f} R')

    print(f'\n\n{"="*90}')
    print('  COMPACT COMPARISON')
    print(f'{"="*90}')
    print(f'  {"Filter":<28}  '
          f'{"--- Training ---":^37}  {"--- Validation ---":^37}')
    print(f'  {"-"*86}')
    _summary_row('Original (all)',      train_all, val_all)
    _summary_row('BUY-only',           train_buy, val_buy)
    _summary_row('BUY-only + UP-regime', train_buu, val_buu)
    print(f'{"="*90}')


if __name__ == '__main__':
    main()
